<a href="https://colab.research.google.com/github/PrettySusi/Proyecto_Integrador/blob/main/Entrega2_automatizaci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importar librerias

import pandas as pd
import kagglehub

In [ ]:
# Descarga el dataset (devuelve la ruta local)
path = kagglehub.dataset_download("steve1215rogg/student-lifestyle-dataset")

# Carga el CSV manualmente
df_academica = pd.read_csv(path + "/student_lifestyle_dataset.csv")

df_academica.head()

Using Colab cache for faster access to the 'student-lifestyle-dataset' dataset.

,Student_ID,Study_Hours_Per_Day,Extracurricular_Hours_Per_Day,Sleep_Hours_Per_Day,Social_Hours_Per_Day,Physical_Activity_Hours_Per_Day,GPA,Stress_Level
0,1,6.9,3.8,8.7,2.8,1.8,2.99,Moderate
1,2,5.3,3.5,8.0,4.2,3.0,2.75,Low
2,3,5.1,3.9,9.2,1.2,4.6,2.67,Low
3,4,6.5,2.1,7.2,1.7,6.5,2.88,Moderate
4,5,8.1,0.6,6.5,2.2,6.6,3.51,High

In [ ]:
# Descarga el dataset (devuelve la ruta local)
path = kagglehub.dataset_download("adilshamim8/social-media-addiction-vs-relationships")

# Carga el CSV manualmente
df_rsociales = pd.read_csv(path + "/Students Social Media Addiction.csv")

df_rsociales.head()

Downloading to /root/.cache/kagglehub/datasets/adilshamim8/social-media-addiction-vs-relationships/3.archive...

100%|██████████| 7.67k/7.67k [00:00<00:00, 8.65MB/s]

Extracting files...

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7